name: Pipeline - Heroku

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  dependency_check:
    runs-on: ubuntu-latest
    continue-on-error: true
    name: Dependency check Scan
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'test'
          path: '.'
          format: 'HTML'    
          args: >
            --failOnCVSS 1
            --enableRetired
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports  
           
  Test:  # Nombre de mi tarea
    runs-on: ubuntu-latest # Donde se va a ejecutar
    steps: # Pasos que se van a ejecutar
    
      # Chequea el repositorio 
      - uses: actions/checkout@v3
      
      - name: PHP Copy Paste Detector
        uses: StephaneBour/actions-php-cpd@1.0
        with:
          dir: '.'
  
  Deploy_production:
    runs-on: ubuntu-latest
    needs: [Test,dependency_check]
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY_FL}}
          heroku_app_name: "tp1-crud-qa" #Must be unique in Heroku
          heroku_email: "carlosdemarino1989@gamil.com"
