
name: Pipeline - Heroku

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
  SONAR_TOKEN : sqp_2405285fa6b915bc6b3dd80dc71c622cd1d637d9
  SONAR_SERVER : http://3.142.156.243:9000
  GITHUB_TOKEN : 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
    
jobs:
  dependency_check:
    runs-on: ubuntu-latest
    continue-on-error: true
    name: Dependency check Scan
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'test'
          path: '.'
          format: 'HTML'    
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports  
   
  SonarScanner:
    runs-on: ubuntu-latest
    name: Sonar Scanner
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: yarn install --production=false
      - name: Scan code
        uses: vtex/action-sonarqube@main
        with:
          githubToken: ${{ env.GITHUB_TOKEN }}
          host: ${{ env.SONAR_SERVER }} 
          token: ${{ env.SONAR_TOKEN }} 
  
  Deploy_production:
    runs-on: ubuntu-latest
    environment: 'Production'
    needs: [dependency_check]
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "tp1-crud-master" #Must be unique in Heroku
          heroku_email: "gastonbarbaccia@hotmail.com"
  
  Acunetix_DAST:
    runs-on: ubuntu-latest
    needs: [Deploy_production]
    steps:
      - name: Trigger Acuneitx Scan
        run: |
             curl -k -i --request POST --url "https://3.134.174.38:3443/api/v1/scans" --header "X-Auth: 1986ad8c0a5b3df4d7028d5f3c06e936c6ee269ab7bdc496db893bb19e349b85b" --header "content-type: application/json" --data '{"profile_id":"11111111-1111-1111-1111-111111111111", "schedule":{"disable":false,"start_date":null,"time_sensitive":false}, "user_authorized_to_scan":"yes", "target_id":"7e7ce4f2-0ac2-4fbf-94ca-3f307747b7ac"}'
